---
- name: Installing base packages
  apt: 
    name: "{{ item }}"
    state: installed
  with_items:
    - tar
    - unzip
    - jq
    - xz-utils
    #Make vagrant compatibubble with 17.10
    - ifupdown 
  become: yes
  become_method: sudo
- name: Configure locales
  shell: |
    locale-gen en_GB.UTF-8
    dpkg-reconfigure -f noninteractive locales
  become: yes
  become_method: sudo
