# vim:ft=ansible:
---
- block:
  - name: Download Packer
    command: "curl -o packer_{{ packer.version }}_linux_amd64.zip https://releases.hashicorp.com/packer/{{ packer.version }}/packer_{{ packer.version }}_linux_amd64.zip"
    args:
      chdir: "/usr/local/bin"
    tags: packer
  - name: Uncompress Packer archive
    unarchive:
      src: "/usr/local/bin/packer_{{ packer.version }}_linux_amd64.zip"
      dest: "/usr/local/bin"
      copy: no
    tags: packer
  become: yes
  become_method: sudo
