# vim:ft=ansible:
---
- name: .bashrc
  copy: src=template.bashrc dest="/home/{{ os.user  }}/.bashrc" owner="{{ os.user  }}" group="{{ os.user  }}" mode=0644
  become: no
- name: Ensure tools
  become: yes
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - git
    - silversearcher-ag
    - imagemagick
    - htop
    - iftop
    - python-pip

- name: Install Powerline Status
  pip:
    name: powerline-shell
  become: yes
  become_method: sudo

- name: Add bash command to bashrc
  become: yes
  become_method: sudo
  blockinfile:
    dest: "/home/{{ os.user  }}/.bashrc"
    block: |
        function _update_ps1() {
            PS1="$(powerline-shell $?)"
        }

        if [ "$TERM" != "linux" ]; then
            PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
        fi
