# vim:ft=ansible:
---
- block:
  - name: Create the rust directory
    file:
      path: "{{ rust_download_dir }}"
      state: directory
      mode: 0755
  - name: Download Rust
    command: "curl -o rust-{{ rust_version }}-x86_64-unknown-linux-gnu.tar.gz https://static.rust-lang.org/dist/rust-{{ rust_version }}-x86_64-unknown-linux-gnu.tar.gz"
    args:
      chdir: "{{ rust_download_dir }}"
    tags: rust

  - name: Uncompress Rust archive
    unarchive:
      src: "{{ rust_download_dir }}/rust-{{ rust_version }}-x86_64-unknown-linux-gnu.tar.gz"
      dest: "{{ rust_download_dir }}"
      copy: no
    tags: rust

  - name: Install Rust
    command: "{{ rust_download_dir }}/rust-{{ rust_version }}-x86_64-unknown-linux-gnu/install.sh"
    args:
      creates: /usr/local/lib/rustlib/uninstall.sh
    tags: rust
  become: true
  become_method: sudo
