---
# tasks file for ansible-role-nodejs
- name: nodejs version
  shell: node --version
  register: node_version
  ignore_errors: yes

- name: is node installed
  set_fact:
    nodejs_install_required: "{{node_version.stdout != nodejs.version}}"

- name: Set node url parameters
  set_fact:
    nodejs:
      source: "https://nodejs.org/dist/{{nodejs.version}}/"
      binary: "node-{{nodejs.version}}-linux-x64.tar.gz"
  when: nodejs_install_required

- name: Download NodeJS
  get_url:
    url: "{{nodejs.source}}{{nodejs.binary}}"
    dest: /usr/local
  when: nodejs_install_required

- name: Install NodeJS
  shell: 'cd /usr/local; tar --strip-components 1 -xzf {{nodejs.binary}}'
  when: nodejs_install_required
