# vim:ft=ansible:
---
#http://everythingshouldbevirtual.com/ansible-rabbitmq-cluster
- name: adding RabbitMQ public GPG key to the apt repo
  become: yes
  become_method: sudo
  apt_key: url=https://www.rabbitmq.com/rabbitmq-release-signing-key.asc state=present

- name: Add rabbitmq sources list
  become: yes
  become_method: sudo
  lineinfile: >
    line="deb http://www.rabbitmq.com/debian/ testing main"
    dest=/etc/apt/sources.list.d/rabbitmq.list
    state=present
    create=yes

- name: installing RabbitMQ server
  become: yes
  become_method: sudo
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    - rabbitmq-server

- name: enabling the RabbitMQ Management Console
  become: yes
  become_method: sudo
  rabbitmq_plugin: names=rabbitmq_management state=enabled
  # notify: restart rabbitmq-server

- name: ubuntu | ensuring that the RabbitMQ service is running
  become: yes
  become_method: sudo
  service: name=rabbitmq-server state=started enabled=yes
