---

#CHECK FOR VARIABLES USING ANSIBLE FAIL & WHEN
- name: precondition - languages
  fail: msg="ERROR - required variable 'languages' missing."
  when: languages is not defined

- name: precondition - languages.java
  fail: msg="ERROR - required variable 'languages.java' missing."
  when: languages.java is not defined

- name: precondition - languages.java.version
  fail: msg="ERROR - required variable 'languages.java.version' missing."
  when: languages.java.version is not defined

- name: precondition - languages.java.gradle
  fail: msg="ERROR - required variable 'languages.java.gradle' missing."
  when: languages.java.gradle is not defined

- name: precondition - languages.java.gradle.version
  fail: msg="ERROR - required variable 'languages.java.gradle.version' missing."
  when: languages.java.gradle.version is not defined

- name: JDK Repository
  become: yes
  become_method: sudo
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'

- name: JDK
  become: yes
  become_method: sudo
  apt: 
    update_cache: yes
    name: "openjdk-{{ languages.java.version  }}-jdk"
    state: installed 
  
- name: Add JAVA Home
  lineinfile: dest=/home/vagrant/.bashrc line="export JAVA_HOME=/usr/lib/jvm/java-{{ languages.java.version  }}-openjdk-amd64" 
  become: no

- name: Add Java Home path to bin path
  lineinfile: dest=/home/vagrant/.bashrc line="export PATH=$PATH:$JAVA_HOME/bin"
  become: no

- name: Download Gradle
  get_url: url=https://services.gradle.org/distributions/gradle-{{ languages.java.gradle.version }}-bin.zip dest=/home/vagrant/gradle-{{ languages.java.gradle.version }}-bin.zip
  become: no

- name: Create the directory for Gradle
  file: path=/usr/local/opt state=directory 
  become: yes
  become_method: sudo

- name: Install Unzip
  become: yes
  become_method: sudo
  apt: 
    name: "unzip"
    state: installed 
  
- name: Unzip Gradle
  unarchive: src=/home/vagrant/gradle-{{ languages.java.gradle.version }}-bin.zip dest=/usr/local/opt/ creates=yes copy=no
  become: yes
  become_method: sudo

- name: Add Gradle Home
  lineinfile: dest=/home/vagrant/.bashrc line="export GRADLE_HOME=/usr/local/opt/gradle-{{ languages.java.gradle.version  }}"
  become: no

- name: Add Gradle Home path to bin path
  lineinfile: dest=/home/vagrant/.bashrc line="export PATH=$PATH:$GRADLE_HOME/bin" 
  become: no
