---

dependencies: []

galaxy_info:

  author: 'Maciej Delmanowski'
  description: 'Manage log rotation configuration'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '2.0.0'

  platforms:

    - name: 'Ubuntu'
      versions: [ 'all' ]

    - name: 'Debian'
      versions: [ 'all' ]

  galaxy_tags:
    - system
    - logs

