---

# create a directory if it doesn't exist
- name: Create VIM directories
  file:
    path: "/home/{{ os.user }}/.vim/ftplugin/"
    state: directory
    mode: 0755
- name: vimrc for Python
  copy: src=python.vim dest="/home/{{ os.user }}/.vim/ftplugin/python.vim" owner="{{ os.user }}" group="{{ os.user }}" mode=0644
  become: no
  when:
    - languages
    - languages.python
- name: pylintrc for Python
  copy: src=pylintrc dest="/home/{{ os.user }}/.pylintrc" owner="{{ os.user }}" group="{{ os.user }}" mode=0644
  become: no
  when:
    - languages
    - languages.python
- name: Python Packages
  pip:
    name: "{{ item  }}"
  with_items:
    - pylint
    - autopep8
    - python-nose2
