# vim:ft=ansible:
---
- name: Add mongo ppa key
  become: yes
  become_method: sudo
  apt_key: >
    keyserver=hkp://keyserver.ubuntu.com:80
    id=0C49F3730359A14518585931BC711F9BA15703C6
    state=present
- name: Add mongo sources list
  become: yes
  become_method: sudo
  lineinfile: >
    line="deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse"
    dest=/etc/apt/sources.list.d/mongodb.list
    state=present
    create=yes
- name: Install mongo
  become: yes
  become_method: sudo
  apt: 
    name: mongodb-org 
    state: installed 
    update_cache: yes
