# vim:ft=ansible:
---
- name: Install list of packages
  become: yes
  become_method: sudo
  apt: 
    name: "{{ item }}"
    state: installed 
    update_cache: yes
  with_items:
  - git
- name: gitconfig
  copy: src=template.gitconfig dest=/home/vagrant/.gitconfig owner=vagrant group=vagrant mode=0644
  become: no
