# vim:ft=ansible:
---
- name: Install list of packages
  become: yes
  become_method: sudo
  apk: 
    name: "{{ item }}"
    state: installed 
    update_cache: yes
  with_items:
  - git
- name: gitconfig
  copy: src=template.gitconfig dest="/home/{{ os.user }}/.gitconfig" owner="{{ os.user }}" group="{{ os.user }}" mode=0644
  become: no
