# vim:ft=ansible:
---
- name: Install list of packages
  become: yes
  become_method: sudo
  apk: 
    name: "{{ item }}"
    state: installed 
    update_cache: yes
  with_items:
  - g++
  - make
  - gcc
  - ncurses-libs
  - python-dev 
  - ruby-dev
  - lua5.1
  - lua5.1-dev
  - perl-dev
  - luajit
  - libluajit-dev
  - git
  - ctags
  - cmake
- name: Checkout VIM source
  become: yes
  become_method: sudo
  git:
    repo: "https://github.com/vim/vim.git"
    dest: /opt/vim
- name: Configure VIM
  become: yes
  become_method: sudo
  shell: |
    ./configure \
    --enable-multibyte \
    --enable-perlinterp=yes \
    --enable-rubyinterp=yes \
    --with-ruby-command=/usr/local/bin/ruby \
    --enable-pythoninterp=yes \
    --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu \
    --enable-luainterp=yes \
    --with-luajit \
    --enable-cscope \
    --enable-gui=auto \
    --with-features=huge \
    --with-x \
    --enable-fontset \
    --enable-largefile \
    --disable-netbeans \
    --with-compiledby="vagrant" \
    --enable-fail-if-missing \
    --prefix=/usr/local &&
    make VIMRUNTIMEDIR=/usr/local/share/vim/vim80 &&
    make install
    chdir=/opt/vim
- name: Ensure vim plugin directory
  file: path="/home/{{ os.user }}/.vim/pack/plugins/start/" state=directory
  become: no
- name: Ensure vim ftplugin directory
  file: path="/home/{{ os.user }}/.vim/ftplugin" state=directory
  become: no
- name: Install base plugins
  become: no
  git: 
    repo: "https://github.com/{{ item.org }}/{{ item.repo }}.git"
    dest: "/home/{{ os.user }}/.vim/pack/plugins/start/{{ item.repo }}"
    depth: 1
  with_items:
    - org: nanotech
      repo: jellybeans.vim
    - org: scrooloose
      repo: nerdtree
    - org: tpope
      repo: vim-fugitive
    - org: majutsushi
      repo: tagbar
    - org: kristijanhusak
      repo: vim-multiple-cursors
    - org: vim-airline
      repo: vim-airline
    - org: airblade
      repo: vim-gitgutter
    - org: kristijanhusak
      repo: vim-multiple-cursors
    - org: nathanaelkane
      repo: vim-indent-guides
    - org: pangloss
      repo: vim-javascript
    - org: artur-shaik
      repo: vim-javacomplete2
    - org: Valloric
      repo: YouCompleteMe
    - org: vim-syntastic
      repo: syntastic
    - org: editorconfig
      repo: editorconfig-vim
    - org: janko-m
      repo: vim-test
    - org: tpope
      repo: vim-dispatch
- name: vimrc
  copy: src=template.vimrc dest="/home/{{ os.user }}/.vimrc" owner="{{ os.user }}" group="{{ os.user }}" mode=0644
  become: no
- name: editor config
  copy: src=template.editorconfig dest="/home/{{ os.user }}/.editorconfig" owner="{{ os.user }}" group="{{ os.user }}" mode=0644
  become: no
- name: Configure YouCompleteMe
  become: yes
  become_method: sudo
  shell: |
    ./install.py 
    chdir=/home/ubuntu/.vim/pack/plugins/start/YouCompleteMe
- name: Delete All the .git directories
  become: no
  shell: |
    cd /home/ubuntu/.vim/pack/plugins/start/
    find -type d -name .git | xargs rm -r
