# vim:ft=ansible:
---
- name: Install list of packages
  become: yes
  become_method: sudo
  apt: 
    name: "{{ item }}"
    state: installed 
    update_cache: yes
  with_items:
  - build-essential
  - libncurses5-dev
  - libgnome2-dev
  - libgnomeui-dev 
  - libgtk2.0-dev
  - libatk1.0-dev
  - libbonoboui2-dev 
  - libcairo2-dev
  - libx11-dev
  - libxpm-dev
  - libxt-dev
  - python-dev 
  - python3-dev
  - ruby-dev
  - lua5.1
  - liblua5.1-dev
  - libperl-dev
  - luajit
  - libluajit-5.1-dev
  - git
  - ctags
  - cmake
- name: Checkout VIM source
  become: yes
  become_method: sudo
  git:
    repo: "https://github.com/vim/vim.git"
    dest: /opt/vim
- name: Configure VIM
  become: yes
  become_method: sudo
  shell: |
    ./configure \
    --enable-multibyte \
    --enable-perlinterp=yes \
    --enable-rubyinterp=yes \
    --with-ruby-command=/usr/local/bin/ruby \
    --enable-pythoninterp=yes \
    --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu \
    #--enable-python3interp=yes \
    #--with-python3-config-dir=/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu \
    --enable-luainterp=yes \
    --with-luajit \
    --enable-cscope \
    --enable-gui=auto \
    --with-features=huge \
    --with-x \
    --enable-fontset \
    --enable-largefile \
    --disable-netbeans \
    --with-compiledby="vagrant" \
    --enable-fail-if-missing \
    --prefix=/usr/local &&
    make VIMRUNTIMEDIR=/usr/local/share/vim/vim80 &&
    make install
    chdir=/opt/vim
- name: Ensure vim plugin directory
  file: path="/home/{{ os.user }}/.vim/pack/plugins/start/" state=directory
  become: no
- name: Ensure vim ftplugin directory
  file: path="/home/{{ os.user }}/.vim/ftplugin" state=directory
  become: no
- name: Install base plugins
  become: no
  git: 
    repo: "https://github.com/{{ item.org }}/{{ item.repo }}.git"
    dest: "/home/{{ os.user }}/.vim/pack/plugins/start/{{ item.repo }}"
  with_items:
    - org: nanotech
      repo: jellybeans.vim
    - org: scrooloose
      repo: nerdtree
    - org: tpope
      repo: vim-fugitive
    - org: majutsushi
      repo: tagbar
    - org: kristijanhusak
      repo: vim-multiple-cursors
    - org: vim-airline
      repo: vim-airline
    - org: airblade
      repo: vim-gitgutter
    - org: kristijanhusak
      repo: vim-multiple-cursors
    - org: nathanaelkane
      repo: vim-indent-guides
    - org: pangloss
      repo: vim-javascript
    - org: artur-shaik
      repo: vim-javacomplete2
    - org: Valloric
      repo: YouCompleteMe
    - org: vim-syntastic
      repo: syntastic
- name: vimrc
  copy: src=template.vimrc dest="/home/{{ os.user }}/.vimrc" owner="{{ os.user }}" group="{{ os.user }}" mode=0644
  become: no
- name: Configure YouCompleteMe
  become: yes
  become_method: sudo
  shell: |
    ./install.py --clang-completer
    chdir=/home/vagrant/.vim/pack/plugins/start/YouCompleteMe
