---
- hosts: all
  vars:
    languages:
      python:
      go: 
        version: '1.8'
      java:
        version: '8'
        gradle:
          version: '2.7' 
  roles:
  # - bash
  # - vim
  # - go
  # - nodejs
  # - git
  #  - mongodb
  #- postgres
  #- rabbitmq
  #- rust
  #- tmux
  #- python
  #- terraform
  #- packer
  - awscli
  #- java
  #- intellij
  #- gnome
